### ISSUE TITLE
Basic filter step is failing

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-qe#147]
```
1) Scenario: Create integration from twitter to salesforce - e2e/integrations/twitter-to-salesforce-integration.feature:42
   Step: And she is presented with a "Basic Filter" step configure page - e2e/integrations/twitter-to-salesforce-integration.feature:77
   Step Definition: node_modules/cucumber-tsflow/src/BindingDecorator.ts:163
   Message:
     AssertionError: Basic Filter page must contain certain elements: expected false to be true
         at /Users/dsimansk/Git/syndesis-e2e-tests/ui-tests-protractor/node_modules/chai-as-promised/lib/chai-as-promised.js:305:22
         at ManagedPromise.invokeCallback_ (/Users/dsimansk/Git/syndesis-e2e-tests/ui-tests-protractor/node_modules/selenium-webdriver/lib/promise.js:1366:14)
         at TaskQueue.execute_ (/Users/dsimansk/Git/syndesis-e2e-tests/ui-tests-protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
         at TaskQueue.executeNext_ (/Users/dsimansk/Git/syndesis-e2e-tests/ui-tests-protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
         at asyncRun (/Users/dsimansk/Git/syndesis-e2e-tests/ui-tests-protractor/node_modules/selenium-webdriver/lib/promise.js:2813:27)
         at /Users/dsimansk/Git/syndesis-e2e-tests/ui-tests-protractor/node_modules/selenium-webdriver/lib/promise.js:676:7
         at <anonymous>
         at process._tickCallback (internal/process/next_tick.js:188:7)

```

@lvydra wdyt?

**Comment by dsimansk** [comment]
@lvydra it's working very nicely now, thanks 👍
